"""Talentrupt PDF builder (campaign report / proposal / one-pager) via reportlab.

Two content paths:
- topic-driven (Create / Chat): an LLM writes tailored, brand-grounded sections via
  ``generate_pdf_outline`` so each document is specific to the request — not a repeated
  template. The outline is generated by the (async) caller and passed in.
- campaign-driven (campaign milestones): renders the campaign's structured strategy.

All dynamic text is XML-escaped because reportlab's Paragraph parses an XML-ish subset.
"""
from __future__ import annotations

from xml.sax.saxutils import escape as _xml_escape

from reportlab.lib import colors
from reportlab.lib.enums import TA_LEFT
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (
    HRFlowable,
    Image as RLImage,
    ListFlowable,
    ListItem,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
)

from ..knowledge import retrieve
from ..models import Brand, Campaign
from ..providers import llm
from .common import logo_path, public_url, storage_subdir, unique_name

NAVY = colors.HexColor("#0B3559")
RED = colors.HexColor("#F6404C")
CREAM = colors.HexColor("#EBE9DF")

KIND_LABELS = {
    "proposal": "Campaign Proposal",
    "one-pager": "Service One-Pager",
    "report": "Campaign Report",
}


def _esc(text) -> str:
    """reportlab Paragraph parses an XML-ish subset; escape dynamic text so &, <, > are safe."""
    return _xml_escape(str(text if text is not None else ""))


def _styles():
    ss = getSampleStyleSheet()
    return {
        "title": ParagraphStyle("trTitle", parent=ss["Title"], textColor=NAVY, fontSize=26, spaceAfter=6),
        "sub": ParagraphStyle("trSub", parent=ss["Normal"], textColor=RED, fontSize=12, spaceAfter=14),
        "h2": ParagraphStyle("trH2", parent=ss["Heading2"], textColor=NAVY, fontSize=15, spaceBefore=14, spaceAfter=6),
        "body": ParagraphStyle("trBody", parent=ss["Normal"], fontSize=10.5, leading=15, alignment=TA_LEFT, spaceAfter=6),
    }


def _heading(flow, st, heading):
    flow.append(Paragraph(_esc(heading), st["h2"]))
    flow.append(HRFlowable(width="20%", thickness=2, color=RED, spaceAfter=6))


def _section(flow, st, heading, content):
    """Heading + rule, then either a bullet list (content is a list) or a paragraph.
    Empty content is skipped entirely so we never emit a dangling heading."""
    if isinstance(content, list):
        items = [ListItem(Paragraph(_esc(c), st["body"]), leftIndent=10) for c in content if str(c).strip()]
        if not items:
            return
        _heading(flow, st, heading)
        flow.append(ListFlowable(items, bulletType="bullet", bulletColor=RED))
    else:
        if not str(content).strip():
            return
        _heading(flow, st, heading)
        flow.append(Paragraph(_esc(content), st["body"]))


async def generate_pdf_outline(brand: Brand | None, topic: str, kind: str) -> dict | None:
    """LLM-write a tailored, brand-grounded document outline for ``topic``.

    Returns ``{"title","subtitle","sections":[{"heading","body","bullets"}]}`` or
    ``None`` when no provider is available / the model returns nothing usable — in
    which case the caller falls back to the template path.
    """
    if not llm.provider_available() or not (topic or "").strip():
        return None
    pillars = ", ".join(brand.pillars) if brand and brand.pillars else ""
    proof = "; ".join(brand.proof_points) if brand and brand.proof_points else ""
    services = ", ".join(brand.services) if brand and brand.services else ""
    context = await retrieve.brand_context(topic, k=6)
    kind_guide = {
        "proposal": (
            "a persuasive CLIENT PROPOSAL: the prospect's situation/problem, Talentrupt's tailored "
            "solution, scope of work, the proof that it works, and a clear next step."
        ),
        "one-pager": (
            "a crisp ONE-PAGE service overview: what it is, who it's for, how it works, the proof, "
            "and a call to action."
        ),
        "report": (
            "an EXECUTIVE BRIEFING / REPORT: the context, the key insight, Talentrupt's approach, "
            "the evidence, and a recommendation."
        ),
    }.get(kind, "an executive document.")
    sys = (
        "You are Talentrupt's senior marketing writer (offshore RPO selling into the US market, "
        f"'RPO Done Right'). Brand pillars: {pillars}. "
        f"Proof points (cite ONLY those directly relevant to THIS topic; never invent numbers): {proof}. "
        f"Services: {services}.\n"
        + (f"\n{context}\n\n" if context else "")
        + f"Write {kind_guide}\n"
        'Return ONLY JSON: {"title": str, "subtitle": str, "sections": '
        '[{"heading": str, "body": str, "bullets": [str]}]} with 4-6 sections. '
        "Each section needs a 'heading', a 'body' of 2-4 SUBSTANTIVE sentences written SPECIFICALLY "
        "for this topic (no generic filler, no repeating the same claim across sections), and OPTIONAL "
        "'bullets' (2-4 concrete points) only where a list genuinely helps. Open with the reader's "
        "problem/context, keep everything specific to the topic, weave in only the most relevant proof "
        "point(s), and close with a concrete call to action. Professional US B2B tone."
    )
    usr = f"Document type: {kind}. Topic / brief: {topic}"
    data = await llm.chat_json(
        [{"role": "system", "content": sys}, {"role": "user", "content": usr}], temperature=0.7
    )
    if not isinstance(data, dict):
        return None
    secs = data.get("sections")
    if not isinstance(secs, list) or not secs:
        return None
    clean = []
    for s in secs:
        if not isinstance(s, dict):
            continue
        heading = str(s.get("heading", "") or "").strip()
        body = str(s.get("body", "") or "").strip()
        bullets = [
            str(b).strip()
            for b in (s.get("bullets") or [])
            if isinstance(b, (str, int, float)) and str(b).strip()
        ]
        if heading and (body or bullets):
            clean.append({"heading": heading, "body": body, "bullets": bullets[:5]})
    if not clean:
        return None
    return {
        "title": (str(data.get("title") or topic).strip() or topic)[:200],
        "subtitle": str(data.get("subtitle") or "").strip()[:300],
        "sections": clean[:7],
    }


def build_pdf(
    brand: Brand | None,
    campaign: Campaign | None,
    kind: str = "report",
    topic: str = "",
    outline: dict | None = None,
) -> tuple[str, str, dict]:
    st = _styles()
    kind_label = KIND_LABELS.get(kind, "Campaign Report")

    file_name = unique_name("tr-doc", "pdf")
    path = storage_subdir("pdfs") / file_name
    doc = SimpleDocTemplate(
        str(path), pagesize=letter,
        topMargin=0.8 * inch, bottomMargin=0.8 * inch,
        leftMargin=0.9 * inch, rightMargin=0.9 * inch,
    )

    flow = []
    try:  # real Talentrupt logo at the top of every document
        flow.append(RLImage(str(logo_path()), width=0.55 * inch, height=0.55 * inch))
    except Exception:
        pass
    flow.append(Paragraph("TR · TALENTRUPT", st["sub"]))

    # --- Path A: LLM-written, topic-specific document -----------------------
    if outline and outline.get("sections"):
        flow.append(Paragraph(_esc(outline.get("title") or topic or "Talentrupt"), st["title"]))
        flow.append(Paragraph(_esc(outline.get("subtitle") or f"{kind_label} · RPO Done Right"), st["sub"]))
        flow.append(HRFlowable(width="100%", thickness=3, color=NAVY, spaceAfter=10))
        for sec in outline["sections"]:
            body = sec.get("body") or ""
            bullets = sec.get("bullets") or []
            if body and bullets:
                _heading(flow, st, sec["heading"])
                flow.append(Paragraph(_esc(body), st["body"]))
                flow.append(ListFlowable(
                    [ListItem(Paragraph(_esc(b), st["body"]), leftIndent=10) for b in bullets],
                    bulletType="bullet", bulletColor=RED,
                ))
            else:
                _section(flow, st, sec["heading"], bullets if bullets else body)
        doc.build(flow)
        return str(path), file_name, {
            "kind": kind, "topic": topic, "url": public_url("pdfs", file_name), "ai_written": True,
        }

    # --- Path B: campaign strategy template (unchanged behavior) ------------
    name = campaign.name if campaign else (topic or "Talentrupt Campaign")
    strat = (campaign.strategy if campaign and campaign.strategy else {}) or {}

    flow.append(Paragraph(_esc(name), st["title"]))
    flow.append(Paragraph(f"{kind_label} · RPO Done Right", st["sub"]))
    flow.append(HRFlowable(width="100%", thickness=3, color=NAVY, spaceAfter=10))

    if strat:
        _section(flow, st, "Objective", strat.get("objective", campaign.goal if campaign else ""))
        _section(flow, st, "Audience & Persona", [strat.get("audience", ""), strat.get("persona", "")])
        if strat.get("pain_points"):
            _section(flow, st, "Pain Points", strat["pain_points"])
        _section(flow, st, "Positioning", strat.get("positioning", ""))
        _section(flow, st, "Key Message", strat.get("key_message", ""))
        if strat.get("content_strategy"):
            _section(flow, st, "Content Strategy", strat["content_strategy"])
        if strat.get("channel_strategy"):
            _section(flow, st, "Channel Strategy", strat["channel_strategy"])
        if strat.get("kpis"):
            _section(flow, st, "KPIs", strat["kpis"])
        if strat.get("recommendations"):
            _section(flow, st, "Recommendations", strat["recommendations"])
    else:
        _section(flow, st, "Overview", topic or (campaign.goal if campaign else "Talentrupt RPO campaign."))
        _section(flow, st, "Services", brand.services if brand else ["Offshore RPO delivery"])

    doc.build(flow)
    return str(path), file_name, {"kind": kind, "url": public_url("pdfs", file_name)}
